name 'ci-btb'
maintainer 'Michael Gutteridge'
maintainer_email 'mrg@fredhutch.org'
license 'all_rights'
description 'Installs/Configures ci-btb'
long_description 'Installs/Configures ci-btb'
version '0.1.13'

depends 'apt'
depends 'apt-chef'
depends 'jenkins', '~> 2.6'
depends 'nginx',  '~> 2.7.9'
depends 'java'
